/// Integration tests for backend-rust.
///
/// The backend now emits a full Rust library crate (3 files):
///   files[0] = Cargo.toml
///   files[1] = src/lib.rs   ← types + Encode/Decode impls
///   files[2] = tests/roundtrip.rs

use std::path::PathBuf;
use backend_rust::RustBackend;
use cddlc_codegen::{Backend, CodegenOptions};
use cddlc_ir::lower;
use cddlc_parser::parse_cddl;

// ── Test helpers ──────────────────────────────────────────────────────────────

struct GeneratedCrate {
    cargo_toml:   String,
    lib_rs:       String,
    roundtrip_rs: String,
}

fn compile(src: &str) -> GeneratedCrate {
    compile_with_opts(src, CodegenOptions::default())
}

fn compile_with_opts(src: &str, opts: CodegenOptions) -> GeneratedCrate {
    let parsed  = parse_cddl(src, PathBuf::from("test.cddl")).expect("parse");
    let lowered = lower(&parsed.value, 16, 64).expect("lower");
    let out     = RustBackend.generate(&lowered.module, &opts).expect("generate");
    assert_eq!(out.files.len(), 3, "expected 3 output files");
    GeneratedCrate {
        cargo_toml:   out.files[0].content.clone(),
        lib_rs:       out.files[1].content.clone(),
        roundtrip_rs: out.files[2].content.clone(),
    }
}

// ── Crate structure ───────────────────────────────────────────────────────────

#[test]
fn test_emits_three_files() {
    let opts = CodegenOptions::default();
    let parsed  = parse_cddl("x = uint", PathBuf::from("t.cddl")).unwrap();
    let lowered = lower(&parsed.value, 16, 64).unwrap();
    let out = RustBackend.generate(&lowered.module, &opts).unwrap();
    assert_eq!(out.files.len(), 3);
    assert!(out.files[0].path.ends_with("Cargo.toml"));
    assert!(out.files[1].path.ends_with("lib.rs"));
    assert!(out.files[2].path.ends_with("roundtrip.rs"));
}

#[test]
fn test_crate_dir_named_after_module() {
    let opts = CodegenOptions::default();
    let parsed  = parse_cddl("x = uint", PathBuf::from("sensor.cddl")).unwrap();
    let lowered = lower(&parsed.value, 16, 64).unwrap();
    let out = RustBackend.generate(&lowered.module, &opts).unwrap();
    assert!(out.files[0].path.starts_with("sensor-cbor/"));
    assert!(out.files[1].path.starts_with("sensor-cbor/src/"));
    assert!(out.files[2].path.starts_with("sensor-cbor/tests/"));
}

// ── Cargo.toml ────────────────────────────────────────────────────────────────

#[test]
fn test_cargo_toml_has_package() {
    let g = compile("device-id = uint");
    assert!(g.cargo_toml.contains("[package]"));
    assert!(g.cargo_toml.contains("edition = \"2021\""));
}

#[test]
fn test_cargo_toml_crate_name() {
    let g = compile("device-id = uint");
    assert!(g.cargo_toml.contains("-cbor"));
}

#[test]
fn test_cargo_toml_minicbor_version_range() {
    let g = compile("device-id = uint");
    assert!(g.cargo_toml.contains(">=0.19"));
}

#[test]
fn test_cargo_toml_heapless_optional() {
    let g = compile("device-id = uint");
    assert!(g.cargo_toml.contains("heapless"));
    assert!(g.cargo_toml.contains("optional = true"));
}

#[test]
fn test_cargo_toml_no_std_feature() {
    let g = compile("device-id = uint");
    assert!(g.cargo_toml.contains("[features]"));
    assert!(g.cargo_toml.contains("no-std"));
}

#[test]
fn test_cargo_toml_dev_dependencies() {
    let g = compile("device-id = uint");
    assert!(g.cargo_toml.contains("[dev-dependencies]"));
}

#[test]
fn test_cargo_toml_dcbor_comment() {
    let mut opts = CodegenOptions::default();
    opts.dcbor = true;
    let g = compile_with_opts("x = uint", opts);
    assert!(g.cargo_toml.contains("dCBOR") || g.cargo_toml.contains("deterministic"));
}

// ── src/lib.rs header ─────────────────────────────────────────────────────────

#[test]
fn test_generates_header() {
    let g = compile("device-id = uint");
    assert!(g.lib_rs.contains("@generated by cddlc"));
    assert!(g.lib_rs.contains("use minicbor"));
}

#[test]
fn test_no_std_is_feature_gated() {
    let g = compile("device-id = uint");
    assert!(g.lib_rs.contains("#![cfg_attr(feature = \"no-std\", no_std)]"));
    assert!(!g.lib_rs.contains("#![no_std]"));
}

#[test]
fn test_heapless_import_is_cfg_gated() {
    let g = compile("device-id = uint");
    assert!(g.lib_rs.contains("#[cfg(feature = \"no-std\")]"));
    assert!(g.lib_rs.contains("use heapless"));
}

// ── Default derives ───────────────────────────────────────────────────────────

#[test]
fn test_struct_derives_default() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.lib_rs.contains("#[derive(Debug, Clone, PartialEq, Default)]"));
}

#[test]
fn test_enum_derives_default() {
    let g = compile(r#"status = "ok" / "warn" / "error""#);
    assert!(g.lib_rs.contains("#[derive(Debug, Clone, PartialEq, Default)]"));
}

#[test]
fn test_enum_first_variant_marked_default() {
    let g = compile(r#"status = "ok" / "warn" / "error""#);
    assert!(g.lib_rs.contains("#[default]"));
}

// ── Type alias ────────────────────────────────────────────────────────────────

#[test]
fn test_simple_alias() {
    let g = compile("device-id = uint");
    assert!(g.lib_rs.contains("pub type DeviceId = u64;"));
}

#[test]
fn test_tstr_alias() {
    let g = compile("label = tstr");
    assert!(g.lib_rs.contains("pub type Label = &str;"));
}

#[test]
fn test_constrained_alias_newtype() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.lib_rs.contains("pub struct DeviceId"));
    assert!(g.lib_rs.contains("impl<'b> Decode<'b, ()> for DeviceId"));
}

#[test]
fn test_constraint_check_in_decode() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.lib_rs.contains("val.len() == 16"));
}

#[test]
fn test_range_constraint_check() {
    let g = compile("temp = int .ge -40 .le 85");
    assert!(g.lib_rs.contains("pub struct Temp"));
    assert!(g.lib_rs.contains("-40"));
    assert!(g.lib_rs.contains("85"));
}

// ── Tagged types ──────────────────────────────────────────────────────────────

#[test]
fn test_tagged_alias() {
    let g = compile("timestamp = #6.1(uint)");
    assert!(g.lib_rs.contains("pub struct Timestamp"));
    assert!(g.lib_rs.contains("Tag::new(1)"));
}

#[test]
fn test_tagged_decode_verifies_tag() {
    let g = compile("timestamp = #6.1(uint)");
    assert!(g.lib_rs.contains("d.tag()?"));
    assert!(g.lib_rs.contains("unexpected CBOR tag"));
}

#[test]
fn test_tagged_encode_emits_tag() {
    let g = compile("timestamp = #6.1(uint)");
    assert!(g.lib_rs.contains("e.tag(minicbor::data::Tag::new(1))?"));
}

// ── Struct ────────────────────────────────────────────────────────────────────

#[test]
fn test_struct_decl() {
    let g = compile("sensor = { id: uint, label: tstr, value: float32 }");
    assert!(g.lib_rs.contains("pub struct Sensor {"));
    assert!(g.lib_rs.contains("pub id: u64,"));
    assert!(g.lib_rs.contains("pub label: &str,"));
    assert!(g.lib_rs.contains("pub value: f32,"));
}

#[test]
fn test_struct_encode_impl() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.lib_rs.contains("impl<W: Write> Encode<W> for Sensor"));
    assert!(g.lib_rs.contains("e.map(2u64)?"));
}

#[test]
fn test_struct_decode_impl() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.lib_rs.contains("impl<'b> Decode<'b, ()> for Sensor"));
    assert!(g.lib_rs.contains("let key = d.str()?"));
    assert!(g.lib_rs.contains("\"id\""));
}

#[test]
fn test_optional_field_is_option() {
    let g = compile("msg = { id: uint, ? label: tstr }");
    assert!(g.lib_rs.contains("pub label: Option<&str>,"));
}

#[test]
fn test_required_field_missing_errors() {
    let g = compile("msg = { id: uint }");
    assert!(g.lib_rs.contains("missing field"));
}

#[test]
fn test_unknown_field_skipped() {
    let g = compile("msg = { id: uint }");
    assert!(g.lib_rs.contains("d.skip()?"));
}

#[test]
fn test_struct_with_ref() {
    let g = compile("device-id = tstr\nsensor = { id: device-id, value: float32 }");
    assert!(g.lib_rs.contains("pub id: DeviceId,"));
}

#[test]
fn test_tagged_struct() {
    let g = compile("tagged-sensor = #6.100({ id: uint, value: float32 })");
    assert!(g.lib_rs.contains("Tag::new(100)"));
    assert!(g.lib_rs.contains("pub struct TaggedSensor"));
}

// ── Enum ──────────────────────────────────────────────────────────────────────

#[test]
fn test_string_enum_decl() {
    let g = compile(r#"status = "ok" / "warn" / "error""#);
    assert!(g.lib_rs.contains("pub enum Status {"));
    assert!(g.lib_rs.contains("Ok("));
    assert!(g.lib_rs.contains("Warn("));
    assert!(g.lib_rs.contains("Error("));
}

#[test]
fn test_string_enum_encode() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.lib_rs.contains("impl<W: Write> Encode<W> for Status"));
    assert!(g.lib_rs.contains("e.str(s)?"));
}

#[test]
fn test_string_enum_decode() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.lib_rs.contains("impl<'b> Decode<'b, ()> for Status"));
    assert!(g.lib_rs.contains("d.str()?"));
}

// ── Array ─────────────────────────────────────────────────────────────────────

#[test]
fn test_array_cfg_gated() {
    let g = compile("; @capacity 8\nreadings = [* float32]");
    assert!(g.lib_rs.contains("#[cfg(not(feature = \"no-std\"))]"));
    assert!(g.lib_rs.contains("#[cfg(feature = \"no-std\")]"));
    assert!(g.lib_rs.contains("heapless::Vec<f32, 8>"));
    assert!(g.lib_rs.contains("Vec<f32>"));
}

#[test]
fn test_array_default_capacity() {
    let g = compile("readings = [* uint]");
    assert!(g.lib_rs.contains("heapless::Vec<u64, 16>"));
}

// ── dCBOR ─────────────────────────────────────────────────────────────────────

#[test]
fn test_dcbor_comment_in_header() {
    let mut opts = CodegenOptions::default();
    opts.dcbor = true;
    let g = compile_with_opts("s = { a: uint, b: tstr }", opts);
    assert!(g.lib_rs.contains("deterministic"));
}

// ── Generics ──────────────────────────────────────────────────────────────────

#[test]
fn test_generic_instantiation_emits_struct() {
    let g = compile("labeled<T> = { label: tstr, value: T }\ntemp-reading = labeled<float32>");
    assert!(g.lib_rs.contains("pub struct TempReading {"));
    assert!(g.lib_rs.contains("pub value: f32,"));
}

// ── Real-world schema ─────────────────────────────────────────────────────────

#[test]
fn test_iot_schema_generates() {
    let g = compile(r#"
sensor-message = {
    version:   uint,
    device-id: device-id,
    timestamp: #6.1(uint),
}
device-id = tstr .size 16
"#);
    assert!(g.lib_rs.contains("pub struct SensorMessage"));
    assert!(g.lib_rs.contains("pub struct DeviceId"));
    assert!(g.lib_rs.contains("val.len() == 16"));
    assert!(g.lib_rs.contains("Tag::new(1)"));
}

// ── Roundtrip test file ───────────────────────────────────────────────────────

#[test]
fn test_roundtrip_file_has_use() {
    let g = compile("sensor = { id: uint }");
    assert!(g.roundtrip_rs.contains("use "));
    assert!(g.roundtrip_rs.contains("_cbor::*"));
}

#[test]
fn test_roundtrip_file_has_generated_comment() {
    let g = compile("sensor = { id: uint }");
    assert!(g.roundtrip_rs.contains("@generated by cddlc"));
}

#[test]
fn test_roundtrip_struct_default_test() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.roundtrip_rs.contains("fn roundtrip_sensor_default()"));
    assert!(g.roundtrip_rs.contains("Sensor::default()"));
    assert!(g.roundtrip_rs.contains("minicbor::encode"));
    assert!(g.roundtrip_rs.contains("minicbor::decode"));
    assert!(g.roundtrip_rs.contains("assert_eq!(original, decoded)"));
}

#[test]
fn test_roundtrip_struct_explicit_test() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.roundtrip_rs.contains("fn roundtrip_sensor_explicit()"));
}

#[test]
fn test_roundtrip_enum_default_test() {
    let g = compile(r#"status = "ok" / "warn" / "error""#);
    assert!(g.roundtrip_rs.contains("fn roundtrip_status_default()"));
    assert!(g.roundtrip_rs.contains("Status::default()"));
}

#[test]
fn test_roundtrip_enum_per_variant_tests() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.roundtrip_rs.contains("roundtrip_status_ok"));
    assert!(g.roundtrip_rs.contains("roundtrip_status_warn"));
}

#[test]
fn test_roundtrip_alias_constraint_test() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.roundtrip_rs.contains("roundtrip_device_id"));
}

#[test]
fn test_roundtrip_tagged_test() {
    let g = compile("timestamp = #6.1(uint)");
    assert!(g.roundtrip_rs.contains("roundtrip_timestamp"));
}

#[test]
fn test_roundtrip_array_cfg_gated() {
    let g = compile("; @capacity 4\nreadings = [* float32]");
    assert!(g.roundtrip_rs.contains("#[cfg(not(feature = \"no-std\"))]"));
    assert!(g.roundtrip_rs.contains("roundtrip_readings"));
}
