/// Rust backend for cddlc.
///
/// Emits a single `.rs` file per CDDL module containing:
///   - Type declarations (structs, enums, type aliases)
///   - `minicbor::Encode` implementations (with optional dCBOR key sorting)
///   - `minicbor::Decode` implementations (with inline validation)
///   - Tag verification on decode, tag emission on encode
///   - `#![no_std]` compatible when `opts.no_std` is true

use cddlc_codegen::{
    capacity_value, constraint_to_rust_check,
    primitive_to_rust, to_pascal_case, to_snake_case, AllocStrategy,
    Backend, CodegenError, CodegenOptions, CodegenOutput, IndentWriter,
};
use cddlc_ir::{
    AliasDef, ArrayDef, Capacity, CborTag, Constraint, EnumDef,
    IrModule, Occurrence, Primitive, StructDef, TypeDef, TypeRef,
};

pub struct RustBackend;

impl Backend for RustBackend {
    fn language_name(&self) -> &str { "Rust" }
    fn file_extension(&self) -> &str { "rs" }

    fn generate(
        &self,
        module: &IrModule,
        opts:   &CodegenOptions,
    ) -> Result<CodegenOutput, CodegenError> {
        let crate_name = format!("{}-cbor", module.name);
        let lib_src    = emit_module(module, opts);
        let tests_src  = emit_roundtrip_tests(module, opts);
        let cargo_toml = emit_cargo_toml(&crate_name, opts);

        Ok(CodegenOutput {
            files: vec![
                cddlc_codegen::GeneratedFile {
                    path:    format!("{}/Cargo.toml", crate_name),
                    content: cargo_toml,
                },
                cddlc_codegen::GeneratedFile {
                    path:    format!("{}/src/lib.rs", crate_name),
                    content: lib_src,
                },
                cddlc_codegen::GeneratedFile {
                    path:    format!("{}/tests/roundtrip.rs", crate_name),
                    content: tests_src,
                },
            ],
        })
    }
}

// ── Module emit ───────────────────────────────────────────────────────────────

fn emit_module(module: &IrModule, opts: &CodegenOptions) -> String {
    let mut w = IndentWriter::new(4);

    // File header
    emit_header(&mut w, opts);

    // Each type definition
    for (name, def) in &module.types {
        w.blank();
        match def {
            TypeDef::Struct(s) => emit_struct(&mut w, s, opts, module),
            TypeDef::Enum(e)   => emit_enum(&mut w, e, opts),
            TypeDef::Array(a)  => emit_array(&mut w, a, opts),
            TypeDef::Alias(a)  => emit_alias(&mut w, a, opts),
            TypeDef::Map(_)    => {
                w.line(&format!("// Map type '{}' — use ArrayDef for open maps", name));
            }
        }
    }

    w.finish()
}

fn emit_header(w: &mut IndentWriter, opts: &CodegenOptions) {
    w.line("// @generated by cddlc — do not edit manually");
    w.line("// Runtime: minicbor");
    if opts.dcbor { w.line("// Encoding: deterministic (dCBOR)"); }
    w.blank();

    // no_std is always feature-gated so the crate works in both environments
    w.line("#![cfg_attr(feature = \"no-std\", no_std)]");
    w.blank();

    w.line("use minicbor::{Decode, Decoder, Encode, Encoder};");
    w.line("use minicbor::decode::Error as DecodeError;");
    w.line("use minicbor::encode::Error as EncodeError;");
    w.line("use minicbor::encode::Write;");
    w.blank();

    // heapless import gated on the no-std feature
    w.line("#[cfg(feature = \"no-std\")]");
    w.line("use heapless::Vec as HVec;");
    w.blank();

    // Error types
    w.line("/// Field-level decode error.");
    w.line("#[derive(Debug, Clone, PartialEq)]");
    w.line("pub struct FieldError {");
    w.indent();
    w.line("pub code:  ErrorCode,");
    w.line("pub field: &'static str,");
    w.line("pub index: Option<usize>,");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
    w.line("pub enum ErrorCode {");
    w.indent();
    w.line("UnexpectedType,");
    w.line("UnexpectedValue,");
    w.line("MissingField,");
    w.line("Overflow,");
    w.line("InvalidUtf8,");
    w.line("UnknownField,");
    w.line("Truncated,");
    w.line("DepthLimit,");
    w.line("TagMismatch,");
    w.line("ValidationFailed,");
    w.dedent();
    w.line("}");
}

// ── Struct ────────────────────────────────────────────────────────────────────

fn emit_struct(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions, module: &IrModule) {
    emit_doc(w, s.doc.as_deref());
    if s.deprecated { w.line("#[deprecated]"); }

    w.line("#[derive(Debug, Clone, PartialEq, Default)]");
    w.line(&format!("pub struct {} {{", to_pascal_case(&s.name)));
    w.indent();
    for f in &s.fields {
        emit_doc(w, f.doc.as_deref());
        let ty_str = field_type_str(&f.ty, &f.occurrence, opts);
        w.line(&format!("pub {}: {},", to_snake_case(&f.name), ty_str));
    }
    w.dedent();
    w.line("}");

    w.blank();
    emit_struct_encode(w, s, opts);
    w.blank();
    emit_struct_decode(w, s, opts, module);
}

fn emit_struct_encode(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(&s.name);
    let field_count = s.fields.len();

    w.line(&format!("impl<C> Encode<C> for {} {{", type_name));
    w.indent();
    w.line("fn encode<W: Write>(&self, e: &mut Encoder<W>, ctx: &mut C) -> Result<(), EncodeError<W::Error>> {");
    w.indent();

    // Emit CBOR tag if present
    if let Some(tag) = s.tagged {
        w.line(&format!("e.tag(minicbor::data::Tag::new({}))?;", tag.0));
    }

    // Count required fields for definite-length map
    w.line(&format!("e.map({}u64)?;", field_count));

    // Emit fields — sorted if dCBOR
    let fields: Vec<_> = if opts.dcbor {
        let mut fs: Vec<_> = s.fields.iter().collect();
        fs.sort_by(|a, b| a.name.cmp(&b.name));
        fs
    } else {
        s.fields.iter().collect()
    };

    for f in &fields {
        let field_access = format!("self.{}", to_snake_case(&f.name));
        w.line(&format!("e.str({:?})?;", f.name.as_str()));
        emit_encode_value(w, &f.ty, &field_access, &f.occurrence, opts);
    }

    w.line("Ok(())");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

fn emit_struct_decode(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions, module: &IrModule) {
    let type_name = to_pascal_case(&s.name);

    w.line(&format!("impl<'b> Decode<'b, ()> for {} {{", type_name));
    w.indent();
    w.line("fn decode(d: &mut Decoder<'b>, ctx: &mut ()) -> Result<Self, DecodeError> {");
    w.indent();

    // Tag verification
    if let Some(tag) = s.tagged {
        w.line(&format!("let t = d.tag()?;"));
        w.line(&format!("if t != minicbor::data::Tag::new({}) {{", tag.0));
        w.indent();
        w.line("return Err(DecodeError::message(\"unexpected CBOR tag\"));");
        w.dedent();
        w.line("}");
    }

    // Declare Option<T> vars for each field.
    // Optional fields already have their final type (e.g. String), so we don't
    // double-wrap with Option<Option<T>>; other occurrences use field_type_str.
    for f in &s.fields {
        let var_ty = match &f.occurrence {
            Occurrence::Optional => typeref_to_rust(&f.ty, opts),
            _ => field_type_str(&f.ty, &f.occurrence, opts),
        };
        w.line(&format!("let mut {}: Option<{}> = None;", to_snake_case(&f.name), var_ty));
    }
    w.blank();

    // Decode map entries
    w.line("let len = d.map()?;");
    w.line("let mut i = 0u64;");
    w.line("loop {");
    w.indent();
    w.line("match len { Some(n) if i >= n => break, None if d.datatype()? == minicbor::data::Type::Break => { d.skip()?; break }, _ => {} }");
    w.line("i += 1;");
    w.line("let key = d.str()?;");
    w.line("match key {");
    w.indent();

    for f in &s.fields {
        let snake = to_snake_case(&f.name);
        w.line(&format!("{:?} => {{", f.name.as_str()));
        w.indent();
        let decode_expr = decode_expr_for_in_module(&f.ty, opts, Some(module));
        w.line(&format!("let val = {};", decode_expr));

        // Inline validation
        emit_field_validation(w, &f.constraints, "val", &f.name);

        w.line(&format!("{snake} = Some(val);"));
        w.dedent();
        w.line("}");
    }

    // Unknown fields — permissive: skip with no error
    w.line("_ => { d.skip()?; }");
    w.dedent();
    w.line("}"); // match key
    w.dedent();
    w.line("}"); // loop
    w.blank();

    // Construct result — required fields unwrap, optional fields map
    w.line("Ok(Self {");
    w.indent();
    for f in &s.fields {
        let snake = to_snake_case(&f.name);
        match &f.occurrence {
            Occurrence::Required => {
                w.line(&format!(
                    "{snake}: {snake}.ok_or_else(|| DecodeError::message(\"missing field '{}'\" ))?,",
                    f.name
                ));
            }
            Occurrence::Optional => {
                w.line(&format!("{snake},"));
            }
            _ => {
                w.line(&format!(
                    "{snake}: {snake}.unwrap_or_default(),",
                ));
            }
        }
    }
    w.dedent();
    w.line("})");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

// ── Enum ──────────────────────────────────────────────────────────────────────

fn emit_enum(w: &mut IndentWriter, e: &EnumDef, opts: &CodegenOptions) {
    emit_doc(w, e.doc.as_deref());
    if e.deprecated { w.line("#[deprecated]"); }

    // Check if first variant is a unit variant (can use #[derive(Default)] + #[default])
    let first_is_unit = e.variants.first().map(|v|
        matches!(&v.ty, TypeRef::Primitive(Primitive::Null))
    ).unwrap_or(true);

    if first_is_unit {
        w.line("#[derive(Debug, Clone, PartialEq, Default)]");
    } else {
        w.line("#[derive(Debug, Clone, PartialEq)]");
    }
    w.line(&format!("pub enum {} {{", to_pascal_case(&e.name)));
    w.indent();
    for (i, v) in e.variants.iter().enumerate() {
        let vname = to_pascal_case(&v.name);
        if i == 0 && first_is_unit { w.line("#[default]"); }
        match &v.ty {
            TypeRef::Primitive(Primitive::Null) => w.line(&format!("{vname},")),
            TypeRef::Primitive(p) => {
                let rt = primitive_to_rust(p, opts.no_std);
                w.line(&format!("{vname}({rt}),"));
            }
            TypeRef::Named(n) => {
                w.line(&format!("{vname}({}),", to_pascal_case(n)));
            }
            _ => w.line(&format!("{vname},")),
        }
    }
    w.dedent();
    w.line("}");

    // If first variant holds data, emit Default manually
    if !first_is_unit {
        if let Some(v) = e.variants.first() {
            let type_name = to_pascal_case(&e.name);
            let vname     = to_pascal_case(&v.name);
            w.blank();
            w.line(&format!("impl Default for {type_name} {{"));
            w.indent();
            w.line("fn default() -> Self {");
            w.indent();
            let default_inner = match &v.ty {
                TypeRef::Primitive(Primitive::Uint) => "0u64".into(),
                TypeRef::Primitive(Primitive::Int)  => "0i64".into(),
                TypeRef::Primitive(Primitive::Bool) => "false".into(),
                TypeRef::Primitive(Primitive::Float | Primitive::Float32 |
                                   Primitive::Float64 | Primitive::Float16) => "0.0".into(),
                TypeRef::Primitive(Primitive::Tstr) => "String::new()".into(),
                TypeRef::Primitive(Primitive::Bstr | Primitive::Any) => "Vec::new()".into(),
                TypeRef::Named(n) => format!("{}::default()", to_pascal_case(n)),
                _ => "Default::default()".into(),
            };
            w.line(&format!("{type_name}::{vname}({default_inner})"));
            w.dedent();
            w.line("}");
            w.dedent();
            w.line("}");
        }
    }

    w.blank();
    emit_enum_encode(w, e, opts);
    w.blank();
    emit_enum_decode(w, e, opts);
}

fn emit_enum_encode(w: &mut IndentWriter, e: &EnumDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(&e.name);
    w.line(&format!("impl<C> Encode<C> for {} {{", type_name));
    w.indent();
    w.line("fn encode<W: Write>(&self, e: &mut Encoder<W>, ctx: &mut C) -> Result<(), EncodeError<W::Error>> {");
    w.indent();

    if let Some(tag) = e.tagged {
        w.line(&format!("e.tag(minicbor::data::Tag::new({}))?;", tag.0));
    }

    w.line("match self {");
    w.indent();
    for v in &e.variants {
        let vname = to_pascal_case(&v.name);
        let type_vname = to_pascal_case(&e.name);
        match &v.ty {
            TypeRef::Primitive(Primitive::Null) => {
                w.line(&format!("{}::{} => {{ e.null()?; }}", type_vname, vname));
            }
            TypeRef::Primitive(Primitive::Tstr) => {
                if opts.no_std {
                    w.line(&format!("{}::{}(s) => {{ e.str(s)?; }}", type_vname, vname));
                } else {
                    w.line(&format!("{}::{}(s) => {{ e.str(s.as_str())?; }}", type_vname, vname));
                }
            }
            TypeRef::Primitive(Primitive::Bstr) => {
                if opts.no_std {
                    w.line(&format!("{}::{}(b) => {{ e.bytes(b)?; }}", type_vname, vname));
                } else {
                    w.line(&format!("{}::{}(b) => {{ e.bytes(b.as_slice())?; }}", type_vname, vname));
                }
            }
            TypeRef::Primitive(Primitive::Bool) => {
                w.line(&format!("{}::{}(b) => {{ e.bool(*b)?; }}", type_vname, vname));
            }
            TypeRef::Primitive(p) if is_integer(p) => {
                w.line(&format!("{}::{}(n) => {{ e.i64(*n as i64)?; }}", type_vname, vname));
            }
            TypeRef::Primitive(p) if is_float(p) => {
                w.line(&format!("{}::{}(f) => {{ e.f64(*f as f64)?; }}", type_vname, vname));
            }
            TypeRef::Named(_) => {
                w.line(&format!("{}::{}(inner) => {{ inner.encode(e, ctx)?; }}", type_vname, vname));
            }
            _ => {
                w.line(&format!("{}::{} => {{ e.null()?; }}", type_vname, vname));
            }
        }
    }
    w.dedent();
    w.line("}");
    w.line("Ok(())");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

fn emit_enum_decode(w: &mut IndentWriter, e: &EnumDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(&e.name);
    w.line(&format!("impl<'b> Decode<'b, ()> for {} {{", type_name));
    w.indent();
    w.line("fn decode(d: &mut Decoder<'b>, ctx: &mut ()) -> Result<Self, DecodeError> {");
    w.indent();

    if let Some(tag) = e.tagged {
        w.line(&format!("let t = d.tag()?;"));
        w.line(&format!("if t != minicbor::data::Tag::new({}) {{", tag.0));
        w.indent();
        w.line("return Err(DecodeError::message(\"unexpected CBOR tag\"));");
        w.dedent();
        w.line("}");
    }

    // Peek at the CBOR type to decide which variant
    w.line("match d.datatype()? {");
    w.indent();

    // Group variants by their expected CBOR type
    let mut has_str   = false;
    let mut has_bool  = false;
    let mut has_int   = false;
    let mut has_map   = false;

    for v in &e.variants {
        match &v.ty {
            TypeRef::Primitive(Primitive::Tstr) => has_str  = true,
            TypeRef::Primitive(Primitive::Bool) => has_bool = true,
            TypeRef::Primitive(p) if is_integer(p) => has_int = true,
            TypeRef::Named(_) => has_map = true,
            _ => {}
        }
    }

    let enum_name = to_pascal_case(&e.name);

    if has_str {
        w.line("minicbor::data::Type::String => {");
        w.indent();
        w.line("let s = d.str()?;");
        w.line("match s {");
        w.indent();
        for v in &e.variants {
            if matches!(&v.ty, TypeRef::Primitive(Primitive::Tstr)) {
                let vname    = to_pascal_case(&v.name);
                let cddl_str = v.name.to_lowercase().replace('_', "-");
                let val: &str = if opts.no_std { "s" } else { "s.to_string()" };
                w.line(&format!("{:?} => Ok({}::{}({val})),", cddl_str, enum_name, vname));
            }
        }
        w.line("_ => Err(DecodeError::message(\"unknown enum variant\")),");
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
    }

    if has_int {
        w.line("minicbor::data::Type::U8 | minicbor::data::Type::U16 |");
        w.line("minicbor::data::Type::U32 | minicbor::data::Type::U64 |");
        w.line("minicbor::data::Type::I8 | minicbor::data::Type::I16 |");
        w.line("minicbor::data::Type::I32 | minicbor::data::Type::I64 => {");
        w.indent();
        // Emit the first integer variant
        for v in &e.variants {
            if let TypeRef::Primitive(p) = &v.ty {
                if is_integer(p) {
                    let vname = to_pascal_case(&v.name);
                    w.line(&format!("Ok({}::{}(d.{}()?))", enum_name, vname, decode_fn_for_primitive(p)));
                    break;
                }
            }
        }
        w.dedent();
        w.line("}");
    }

    if has_bool {
        w.line("minicbor::data::Type::Bool => {");
        w.indent();
        for v in &e.variants {
            if matches!(&v.ty, TypeRef::Primitive(Primitive::Bool)) {
                let vname = to_pascal_case(&v.name);
                w.line(&format!("Ok({}::{}(d.bool()?))", enum_name, vname));
                break;
            }
        }
        w.dedent();
        w.line("}");
    }

    if has_map {
        w.line("_ => Err(DecodeError::message(\"unsupported enum variant type\")),");
    } else {
        w.line("_ => Err(DecodeError::message(\"unexpected CBOR type for enum\")),");
    }

    w.dedent();
    w.line("}"); // match datatype
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

// ── Array ─────────────────────────────────────────────────────────────────────

fn emit_array(w: &mut IndentWriter, a: &ArrayDef, opts: &CodegenOptions) {
    emit_doc(w, a.doc.as_deref());
    if a.deprecated { w.line("#[deprecated]"); }

    let type_name = to_pascal_case(&a.name);
    let elem_ty   = typeref_to_rust(&a.element, opts);
    let cap       = capacity_value(
        a.occurrence.capacity().unwrap_or(&Capacity::Bounded(opts.max_array)),
        opts.max_array,
    );

    // Emit both forms, gated on the no-std feature
    w.line("#[cfg(not(feature = \"no-std\"))]");
    w.line(&format!("pub type {} = Vec<{}>;", type_name, elem_ty));
    w.line("#[cfg(feature = \"no-std\")]");
    w.line(&format!(
        "pub type {} = heapless::Vec<{}, {}>;",
        type_name, elem_ty, cap
    ));
}

// ── Alias ─────────────────────────────────────────────────────────────────────

fn emit_alias(w: &mut IndentWriter, a: &AliasDef, opts: &CodegenOptions) {
    emit_doc(w, a.doc.as_deref());
    if a.deprecated { w.line("#[deprecated]"); }

    let type_name = to_pascal_case(&a.name);

    // If there's a tag, wrap in a newtype struct
    if let Some(tag) = a.tagged {
        let inner_ty = typeref_to_rust(&a.ty, opts);
        w.line("#[derive(Debug, Clone, PartialEq, Default)]");
        w.line(&format!("pub struct {}(pub {});", type_name, inner_ty));
        w.blank();
        emit_tagged_newtype_encode(w, &type_name, tag, &a.ty, opts);
        w.blank();
        emit_tagged_newtype_decode(w, &type_name, tag, &a.ty, &a.constraints, opts);
    } else if a.constraints.is_empty() {
        // Simple type alias
        let inner_ty = typeref_to_rust(&a.ty, opts);
        w.line(&format!("pub type {} = {};", type_name, inner_ty));
    } else {
        // Constrained alias — newtype with validation
        let inner_ty = typeref_to_rust(&a.ty, opts);
        w.line("#[derive(Debug, Clone, PartialEq, Default)]");
        w.line(&format!("pub struct {}(pub {});", type_name, inner_ty));
        w.blank();
        emit_constrained_newtype_encode(w, &type_name, &a.ty, opts);
        w.blank();
        emit_constrained_newtype_decode(w, &type_name, &a.ty, &a.constraints, opts);
    }
}

// ── Tagged newtype impl ───────────────────────────────────────────────────────

fn emit_tagged_newtype_encode(
    w:         &mut IndentWriter,
    type_name: &str,
    tag:       CborTag,
    inner:     &TypeRef,
    opts:      &CodegenOptions,
) {
    w.line(&format!("impl<C> Encode<C> for {} {{", type_name));
    w.indent();
    w.line("fn encode<W: Write>(&self, e: &mut Encoder<W>, ctx: &mut C) -> Result<(), EncodeError<W::Error>> {");
    w.indent();
    w.line(&format!("e.tag(minicbor::data::Tag::new({}))?;", tag.0));
    emit_encode_value(w, inner, "self.0", &Occurrence::Required, opts);
    w.line("Ok(())");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

fn emit_tagged_newtype_decode(
    w:           &mut IndentWriter,
    type_name:   &str,
    tag:         CborTag,
    inner:       &TypeRef,
    constraints: &[Constraint],
    opts:        &CodegenOptions,
) {
    w.line(&format!("impl<'b> Decode<'b, ()> for {} {{", type_name));
    w.indent();
    w.line("fn decode(d: &mut Decoder<'b>, ctx: &mut ()) -> Result<Self, DecodeError> {");
    w.indent();
    w.line("let t = d.tag()?;");
    w.line(&format!("if t != minicbor::data::Tag::new({}) {{", tag.0));
    w.indent();
    w.line("return Err(DecodeError::message(\"unexpected CBOR tag\"));");
    w.dedent();
    w.line("}");
    let decode_expr = decode_expr_for(inner, opts);
    w.line(&format!("let val = {};", decode_expr));
    emit_field_validation(w, constraints, "val", type_name);
    w.line("Ok(Self(val))");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

fn emit_constrained_newtype_encode(
    w:         &mut IndentWriter,
    type_name: &str,
    inner:     &TypeRef,
    opts:      &CodegenOptions,
) {
    w.line(&format!("impl<C> Encode<C> for {} {{", type_name));
    w.indent();
    w.line("fn encode<W: Write>(&self, e: &mut Encoder<W>, ctx: &mut C) -> Result<(), EncodeError<W::Error>> {");
    w.indent();
    emit_encode_value(w, inner, "self.0", &Occurrence::Required, opts);
    w.line("Ok(())");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

fn emit_constrained_newtype_decode(
    w:           &mut IndentWriter,
    type_name:   &str,
    inner:       &TypeRef,
    constraints: &[Constraint],
    opts:        &CodegenOptions,
) {
    w.line(&format!("impl<'b> Decode<'b, ()> for {} {{", type_name));
    w.indent();
    w.line("fn decode(d: &mut Decoder<'b>, ctx: &mut ()) -> Result<Self, DecodeError> {");
    w.indent();
    let decode_expr = decode_expr_for(inner, opts);
    w.line(&format!("let val = {};", decode_expr));
    emit_field_validation(w, constraints, "val", type_name);
    w.line("Ok(Self(val))");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

// ── Encode helpers ────────────────────────────────────────────────────────────

fn emit_encode_value(
    w:      &mut IndentWriter,
    ty:     &TypeRef,
    expr:   &str,
    occ:    &Occurrence,
    opts:   &CodegenOptions,
) {
    match occ {
        Occurrence::Optional => {
            w.line(&format!("if let Some(ref v) = {expr} {{"));
            w.indent();
            emit_encode_typeref(w, ty, "v", opts);
            w.dedent();
            w.line("} else { e.null()?; }");
        }
        Occurrence::ZeroOrMore { .. }
        | Occurrence::OneOrMore { .. }
        | Occurrence::Bounded { .. } => {
            w.line(&format!("e.array({expr}.len() as u64)?;"));
            w.line(&format!("for item in {expr}.iter() {{"));
            w.indent();
            emit_encode_typeref(w, ty, "item", opts);
            w.dedent();
            w.line("}");
        }
        Occurrence::Required => {
            emit_encode_typeref(w, ty, expr, opts);
        }
    }
}

fn emit_encode_typeref(w: &mut IndentWriter, ty: &TypeRef, expr: &str, opts: &CodegenOptions) {
    match ty {
        TypeRef::Primitive(p) => {
            let enc = encode_call_for_primitive(p, expr);
            w.line(&format!("{enc}?;"));
        }
        TypeRef::Named(_) => {
            w.line(&format!("{expr}.encode(e, ctx)?;"));
        }
        TypeRef::Tagged(tag, inner) => {
            w.line(&format!("e.tag(minicbor::data::Tag::new({}))?;", tag.0));
            emit_encode_typeref(w, inner, expr, opts);
        }
        TypeRef::Choice(_) => {
            // Can't determine variant at compile time — encode as-is
            w.line(&format!("{expr}.encode(e, ctx)?;"));
        }
    }
}

fn encode_call_for_primitive(p: &Primitive, expr: &str) -> String {
    match p {
        Primitive::Bool    => format!("e.bool({expr})"),
        Primitive::Null | Primitive::Undefined => "e.null()".into(),
        Primitive::Uint    => format!("e.u64({expr})"),
        Primitive::Int     => format!("e.i64({expr})"),
        Primitive::Float16 | Primitive::Float32 => format!("e.f32({expr})"),
        Primitive::Float64 | Primitive::Float   => format!("e.f64({expr})"),
        // For owned String / Vec<u8>, borrow as &str / &[u8]
        Primitive::Tstr    => format!("e.str({expr}.as_str())"),
        Primitive::Bstr    => format!("e.bytes({expr}.as_slice())"),
        Primitive::Any     => format!("e.bytes({expr}.as_slice())"),
    }
}

// ── Decode helpers ────────────────────────────────────────────────────────────

fn decode_expr_for(ty: &TypeRef, opts: &CodegenOptions) -> String {
    decode_expr_for_in_module(ty, opts, None)
}

fn decode_expr_for_in_module(ty: &TypeRef, opts: &CodegenOptions, module: Option<&IrModule>) -> String {
    match ty {
        TypeRef::Primitive(p) => {
            let fn_name = decode_fn_for_primitive(p);
            match p {
                // Owned String types need .to_string() / .to_vec()
                Primitive::Tstr if !opts.no_std =>
                    format!("d.str()?.to_string()"),
                Primitive::Bstr | Primitive::Any if !opts.no_std =>
                    format!("d.bytes()?.to_vec()"),
                _ => format!("d.{fn_name}()?"),
            }
        }
        TypeRef::Named(n) => {
            // Array type aliases (Vec<T>) decode via minicbor's blanket impl
            let is_array = module.and_then(|m| m.get(n))
                .map(|def| matches!(def, TypeDef::Array(_)))
                .unwrap_or(false);
            if is_array {
                format!("d.decode()?")
            } else {
                format!("{}::decode(d, ctx)?", to_pascal_case(n))
            }
        }
        TypeRef::Tagged(_, inner) => decode_expr_for_in_module(inner, opts, module),
        TypeRef::Choice(_) => "d.decode()?".into(),
    }
}

fn decode_fn_for_primitive(p: &Primitive) -> &'static str {
    match p {
        Primitive::Bool               => "bool",
        Primitive::Null | Primitive::Undefined => "null",
        Primitive::Uint               => "u64",
        Primitive::Int                => "i64",
        Primitive::Float16            => "f32",
        Primitive::Float32            => "f32",
        Primitive::Float64 | Primitive::Float => "f64",
        Primitive::Bstr               => "bytes",
        Primitive::Tstr               => "str",
        Primitive::Any                => "bytes",
    }
}

fn emit_field_validation(
    w:          &mut IndentWriter,
    constraints: &[Constraint],
    val_expr:   &str,
    field_name: &str,
) {
    for c in constraints {
        if let Some(check) = constraint_to_rust_check(c, val_expr) {
            w.line(&format!("if !({check}) {{"));
            w.indent();
            w.line(&format!(
                "return Err(DecodeError::message(\"validation failed for field '{}'\"));",
                field_name
            ));
            w.dedent();
            w.line("}");
        }
    }
}

// ── Type string helpers ───────────────────────────────────────────────────────

fn field_type_str(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    let base = typeref_to_rust(ty, opts);
    match occ {
        Occurrence::Optional => format!("Option<{base}>"),
        Occurrence::ZeroOrMore { capacity } | Occurrence::OneOrMore { capacity }
        | Occurrence::Bounded { capacity, .. } => {
            let cap = capacity_value(capacity, opts.max_array);
            // In the generated crate, the type depends on the no-std feature.
            // We emit the std form here; the no-std form is handled at the
            // type alias level via #[cfg] in emit_array.
            // For struct fields we pick based on alloc strategy at codegen time.
            if opts.no_std || opts.alloc == AllocStrategy::Stack || opts.alloc == AllocStrategy::Arena {
                format!("heapless::Vec<{base}, {cap}>")
            } else {
                format!("Vec<{base}>")
            }
        }
        Occurrence::Required => base,
    }
}

fn typeref_to_rust(ty: &TypeRef, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p)  => primitive_to_rust(p, opts.no_std).to_owned(),
        TypeRef::Named(n)      => to_pascal_case(n),
        TypeRef::Tagged(_, inner) => typeref_to_rust(inner, opts),
        TypeRef::Choice(cs)    => {
            // Inline choices are rare in field position; use the first variant
            cs.first()
                .map(|c| typeref_to_rust(c, opts))
                .unwrap_or_else(|| "()".into())
        }
    }
}

fn is_integer(p: &Primitive) -> bool {
    matches!(p, Primitive::Uint | Primitive::Int)
}

fn is_float(p: &Primitive) -> bool {
    matches!(p, Primitive::Float | Primitive::Float16 | Primitive::Float32 | Primitive::Float64)
}

fn emit_doc(w: &mut IndentWriter, doc: Option<&str>) {
    if let Some(d) = doc {
        for line in d.lines() {
            w.line(&format!("/// {line}"));
        }
    }
}
// ── Cargo.toml generation ─────────────────────────────────────────────────────

fn emit_cargo_toml(crate_name: &str, opts: &CodegenOptions) -> String {
    let mut s = String::new();
    s.push_str("# @generated by cddlc — do not edit manually\n");
    s.push_str("[package]\n");
    s.push_str(&format!("name    = {:?}\n", crate_name));
    s.push_str("version = \"0.1.0\"\n");
    s.push_str("edition = \"2021\"\n");
    s.push('\n');
    s.push_str("[dependencies]\n");
    s.push_str("minicbor = { version = \">=2\", features = [\"derive\"] }\n");
    s.push_str("heapless = { version = \"0.8\", optional = true }\n");
    s.push('\n');
    s.push_str("[features]\n");
    s.push_str("default = []\n");
    s.push_str("no-std  = [\"heapless\"]\n");
    s.push('\n');
    s.push_str("[dev-dependencies]\n");
    s.push_str("minicbor = { version = \">=2\", features = [\"derive\", \"alloc\"] }\n");
    if opts.dcbor {
        s.push('\n');
        s.push_str("# dCBOR deterministic encoding enabled\n");
    }
    s
}

// ── Roundtrip test generation ─────────────────────────────────────────────────

fn emit_roundtrip_tests(module: &IrModule, opts: &CodegenOptions) -> String {
    let mut w = IndentWriter::new(4);
    let crate_name = format!("{}_cbor", module.name.replace('-', "_"));

    w.line("// @generated by cddlc — do not edit manually");
    w.line("// Roundtrip encode/decode tests");
    w.blank();
    w.line(&format!("use {}::*;", crate_name));
    w.blank();

    for (_, def) in &module.types {
        match def {
            TypeDef::Struct(s) => emit_struct_roundtrip(&mut w, s, opts),
            TypeDef::Enum(e)   => emit_enum_roundtrip(&mut w, e, opts),
            TypeDef::Alias(a)  => emit_alias_roundtrip(&mut w, a, opts),
            TypeDef::Array(a)  => emit_array_roundtrip(&mut w, a, opts),
            TypeDef::Map(_)    => {}
        }
        w.blank();
    }

    w.finish()
}

fn emit_struct_roundtrip(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(&s.name);
    let test_name = format!("roundtrip_{}", to_snake_case(&s.name));

    // Tier 1: default roundtrip
    w.line("#[test]");
    w.line(&format!("fn {test_name}_default() {{"));
    w.indent();
    w.line(&format!("let original = {}::default();", type_name));
    w.line("let mut buf = Vec::new();");
    w.line("minicbor::encode(&original, &mut buf).expect(\"encode\");");
    w.line(&format!(
        "let decoded: {} = minicbor::decode(&buf).expect(\"decode\");",
        type_name
    ));
    w.line("assert_eq!(original, decoded);");
    w.dedent();
    w.line("}");
    w.blank();

    // Tier 2: explicit values test
    w.line("#[test]");
    w.line(&format!("fn {test_name}_explicit() {{"));
    w.indent();
    w.line(&format!("let original = {} {{", type_name));
    w.indent();
    for f in &s.fields {
        let fname = to_snake_case(&f.name);
        let val   = default_value_expr(&f.ty, &f.occurrence, opts);
        w.line(&format!("{fname}: {val},"));
    }
    w.dedent();
    w.line("};");
    w.line("let mut buf = Vec::new();");
    w.line("minicbor::encode(&original, &mut buf).expect(\"encode\");");
    w.line(&format!(
        "let decoded: {} = minicbor::decode(&buf).expect(\"decode\");",
        type_name
    ));
    w.line("assert_eq!(original, decoded);");

    // Tag presence check
    if let Some(tag) = s.tagged {
        w.blank();
        w.line("// Verify CBOR tag is present in encoded bytes");
        w.line(&format!("assert!(buf[..n].contains(&0xc0u8.wrapping_add({}u8)), \"tag {} not found\");",
            tag.0 % 24, tag.0));
    }
    w.dedent();
    w.line("}");
}

fn emit_enum_roundtrip(w: &mut IndentWriter, e: &EnumDef, _opts: &CodegenOptions) {
    let type_name = to_pascal_case(&e.name);
    let test_name = format!("roundtrip_{}", to_snake_case(&e.name));

    w.line("#[test]");
    w.line(&format!("fn {test_name}_default() {{"));
    w.indent();
    w.line(&format!("let original = {}::default();", type_name));
    w.line("let mut buf = Vec::new();");
    w.line("minicbor::encode(&original, &mut buf).expect(\"encode\");");
    w.line(&format!(
        "let decoded: {} = minicbor::decode(&buf).expect(\"decode\");",
        type_name
    ));
    w.line("assert_eq!(original, decoded);");
    w.dedent();
    w.line("}");

    // Test each variant
    for v in &e.variants {
        let vname     = to_pascal_case(&v.name);
        let var_test  = format!("roundtrip_{}_{}", to_snake_case(&e.name), v.name.to_lowercase().replace('-', "_"));
        let construct = match &v.ty {
            TypeRef::Primitive(Primitive::Tstr) => {
                // Use variant name lowercased as the string value
                let s = v.name.to_lowercase().replace('_', "-");
                format!("{}::{}({:?}.to_string())", type_name, vname, s)
            }
            TypeRef::Primitive(Primitive::Uint) =>
                format!("{}::{}(0u64)", type_name, vname),
            TypeRef::Primitive(Primitive::Int) =>
                format!("{}::{}(0i64)", type_name, vname),
            TypeRef::Primitive(Primitive::Bool) =>
                format!("{}::{}(false)", type_name, vname),
            TypeRef::Primitive(Primitive::Null) =>
                format!("{}::{}", type_name, vname),
            _ => continue,
        };

        w.blank();
        w.line("#[test]");
        w.line(&format!("fn {var_test}() {{"));
        w.indent();
        w.line(&format!("let original = {construct};"));
        w.line("let mut buf = Vec::new();");
        w.line("minicbor::encode(&original, &mut buf).expect(\"encode\");");
        w.line(&format!(
            "let decoded: {} = minicbor::decode(&buf).expect(\"decode\");",
            type_name
        ));
        w.line("assert_eq!(original, decoded);");
        w.dedent();
        w.line("}");
    }
}

fn emit_alias_roundtrip(w: &mut IndentWriter, a: &AliasDef, _opts: &CodegenOptions) {
    if a.constraints.is_empty() && a.tagged.is_none() {
        return; // simple alias — no interesting test to write
    }

    let type_name = to_pascal_case(&a.name);
    let test_name = format!("roundtrip_{}", to_snake_case(&a.name));

    // Tier 1: default roundtrip (constrained newtype)
    w.line("#[test]");
    w.line(&format!("fn {test_name}_default() {{"));
    w.indent();
    w.line(&format!("let original = {}::default();", type_name));
    w.line("let mut buf = Vec::new();");
    w.line("minicbor::encode(&original, &mut buf).expect(\"encode\");");
    w.line(&format!(
        "let decoded: {} = minicbor::decode(&buf).expect(\"decode\");",
        type_name
    ));
    w.line("assert_eq!(original, decoded);");
    w.dedent();
    w.line("}");

    // Tag verification test
    if let Some(tag) = a.tagged {
        w.blank();
        w.line("#[test]");
        w.line(&format!("fn {test_name}_tag_present() {{"));
        w.indent();
        w.line(&format!("let original = {}::default();", type_name));
        w.line("let mut buf = Vec::new();");
        w.line("minicbor::encode(&original, &mut buf).expect(\"encode\");");
        w.line(&format!("// CBOR tag({}) must be the first byte group", tag.0));
        w.line("assert!(n >= 2, \"encoded output too short to contain tag\");");
        w.dedent();
        w.line("}");
    }

    // Tier 2: constraint violation test (valid value roundtrips, invalid rejected)
    for c in &a.constraints {
        match c {
            cddlc_ir::Constraint::SizeExact(n) => {
                let valid_val = match &a.ty {
                    TypeRef::Primitive(Primitive::Tstr) =>
                        format!("{:?}.to_string()", "a".repeat(*n)),
                    TypeRef::Primitive(Primitive::Bstr) =>
                        format!("vec![0u8; {}]", n),
                    _ => continue,
                };
                w.blank();
                w.line("#[test]");
                w.line(&format!("fn {test_name}_valid_size() {{"));
                w.indent();
                w.line(&format!("let original = {}({});", type_name, valid_val));
                w.line("let mut buf = Vec::new();");
                w.line("minicbor::encode(&original, &mut buf).expect(\"encode\");");
                w.line(&format!(
                    "let decoded: {} = minicbor::decode(&buf[..n]).expect(\"decode valid\");",
                    type_name
                ));
                w.line("assert_eq!(original, decoded);");
                w.dedent();
                w.line("}");
            }
            cddlc_ir::Constraint::ValueRangeInt { min, max, .. } => {
                if let Some(lo) = min {
                    let mid = if let Some(hi) = max { (lo + hi) / 2 } else { *lo };
                    w.blank();
                    w.line("#[test]");
                    w.line(&format!("fn {test_name}_in_range() {{"));
                    w.indent();
                    w.line(&format!("let original = {}({mid}i64);", type_name));
                    w.line("let mut buf = Vec::new();");
                    w.line("minicbor::encode(&original, &mut buf).expect(\"encode\");");
                    w.line(&format!(
                        "let decoded: {} = minicbor::decode(&buf).expect(\"decode\");",
                        type_name
                    ));
                    w.line("assert_eq!(original, decoded);");
                    w.dedent();
                    w.line("}");
                }
            }
            _ => {}
        }
    }
}

fn emit_array_roundtrip(w: &mut IndentWriter, a: &ArrayDef, _opts: &CodegenOptions) {
    // Arrays are type aliases — test via the element type directly
    let type_name = to_pascal_case(&a.name);
    let test_name = format!("roundtrip_{}", to_snake_case(&a.name));

    w.line("#[cfg(not(feature = \"no-std\"))]");
    w.line("#[test]");
    w.line(&format!("fn {test_name}_empty() {{"));
    w.indent();
    w.line(&format!("let original: {} = Vec::new();", type_name));
    w.line("let mut buf = Vec::new();");
    w.line("minicbor::encode(&original, &mut buf).expect(\"encode\");");
    w.line(&format!(
        "let decoded: {} = minicbor::decode(&buf).expect(\"decode\");",
        type_name
    ));
    w.line("assert_eq!(original, decoded);");
    w.dedent();
    w.line("}");
}

// ── Default value expression helpers ─────────────────────────────────────────

fn default_value_expr(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    match occ {
        Occurrence::Optional => "None".into(),
        Occurrence::ZeroOrMore { .. } | Occurrence::OneOrMore { .. }
        | Occurrence::Bounded { .. } => {
            if opts.no_std || opts.alloc == AllocStrategy::Stack
                || opts.alloc == AllocStrategy::Arena
            {
                "heapless::Vec::new()".into()
            } else {
                "Vec::new()".into()
            }
        }
        Occurrence::Required => primitive_default_expr(ty),
    }
}

fn primitive_default_expr(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Primitive(p) => match p {
            Primitive::Bool               => "false".into(),
            Primitive::Null | Primitive::Undefined => "()".into(),
            Primitive::Uint               => "0u64".into(),
            Primitive::Int                => "0i64".into(),
            Primitive::Float16 | Primitive::Float32 => "0.0f32".into(),
            Primitive::Float64 | Primitive::Float   => "0.0f64".into(),
            Primitive::Bstr | Primitive::Any        => "b\"\"".into(),
            Primitive::Tstr               => "\"\"".into(),
        },
        TypeRef::Named(n)      => format!("{}::default()", to_pascal_case(n)),
        TypeRef::Tagged(_, inner) => primitive_default_expr(inner),
        TypeRef::Choice(cs)    => cs.first()
            .map(primitive_default_expr)
            .unwrap_or_else(|| "Default::default()".into()),
    }
}
